from tkinter import *
import asignar_var
w=Tk()
w.geometry("500x500")
texto= StringVar()
text=StringVar()

l= Label(w, text="Proyecto Lenguajes de Programación: Java Funcional",font="Helvfont",justify="center")
l.grid(row=0,column=0)
img = PhotoImage(file="Java.png")
widget = Label(w, image=img).grid(row=1,column=0)
l1= Label(w, text="Se puede ingresar las siguientes estructuras:",font="Helvfont",justify="right")
l1.grid(row=2,column=0)
l2= Label(w, text="•ArrayList.",font="Helvfont",justify="right")
l2.grid(row=3,column=0)
l3= Label(w, text="•LinkedList.",font="Helvfont",justify="right")
l3.grid(row=4,column=0)
l4= Label(w, text="•DoubleLinkedList",font="Helvfont",justify="right")
l4.grid(row=5,column=0)
l5= Label(w, text="•Stack.",font="Helvfont",justify="right")
l5.grid(row=6,column=0)
l6= Label(w, text="•Queue.",font="Helvfont",justify="right")
l6.grid(row=7,column=0)
l7= Label(w, text="Ingrese su cadena: ",font="Helvfont",justify="right")
l7.grid(row=8,column=0)
f=Entry(w, textvar=texto)
f.grid(row=21,column=1)
b1=Button(w, text="Ingresar",command=lambda: asignar_var(texto.get(), text))
b1.grid(row=23,column=1)
w.mainloop()
